### ISSUE TITLE
quora limited questions/answers

### ISSUE THREAD

**Issue by muhamed-didovic** [Leozw12/quora_distributed_crawler#1]
hey @Leozw12, 

thanks for great tool.
I was wondering do we get limited number of questions/answers from API and if yes how to overcome it?

**Comment by Leozw12** [comment]
Hi @muhamed-didovic 
I think we can get all the questions and answers from Quora, but for now, frequent requests may result in Quora ban the IP. I am trying to overcome this.

**Comment by muhamed-didovic** [comment]
hey @muhamed-didovic 
I am also getting the infamous 429 error when hitting a little bit hard, anyways when I have for example this search: https://www.quora.com/search?q=socrates, I get around 295 questions and for each question I get 75 answers, which makes no sense, I use the same endpoints like you

**Comment by Leozw12** [comment]
Hi @muhamed-didovic 
You might need to appropriately control the request frequency and incorporate a request retry mechanism,  much like I do.
I also encounter the 403 error, which could result in my IP being unable to access Quora for an entire day.

**Comment by muhamed-didovic** [comment]
@Leozw12, sure I agree, I build back-off mechanisam when hitting 429, I am just concerned do I actually get all questions and answers for search terms, do you have any suggestion or tips on this subject, or how would you confirm that quora listed all questions with answers?

**Comment by Leozw12** [comment]
Hi @muhamed-didovic 
We can use the question ID to get the question and its answers. The ID is a sequential series starting with 902.
You can look here -> https://github.com/leozw12/quora_distributed_crawler/blob/main/api/answer.py.
